server:
  port: 7076

spring:
  application:
    name: service-feign

  zipkin:
    base-url: http://localhost:7082

  sleuth:
    sampler:
      percentage: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7070/eureka/
  instance:
    hostname: localhost

feign:
   hystrix:
     enabled: true
