
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/spring-cloud-zipkin?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password:
#    driver-class-name: com.mysql.jdbc.Driver

#zipkin:
#  storage:
#    type: mysql

server:
  port: 7082

#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest