server:
  port: 7075

spring:
  application:
    name: service-ribbon

  zipkin:
    base-url: http://localhost:7082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7070/eureka/
  instance:
    hostname: localhost