server:
  port: 7071

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:7070/eureka/
#       defaultZone发现服务的host改为镜像名 eureka-server
#      defaultZone: http://spring-cloud-eureka-server:7070/eureka/

spring:
  application:
    # 需要指明spring.application.name,这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
    name: service-hi
  profiles:
    active:

  zipkin:
    base-url: http://localhost:7082


#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest


